[MULTI:REVIEW] Workflow: add better err handling

diff --git a/.github/workflows/indexer-reusable-build-and-run-docker-image.yml b/.github/workflows/indexer-reusable-build-and-run-docker-image.yml
--- a/.github/workflows/indexer-reusable-build-and-run-docker-image.yml
+++ b/.github/workflows/indexer-reusable-build-and-run-docker-image.yml
@@ -83,10 +83,18 @@ jobs:
         # `timeout` sends a `SIGTERM` to the process, resulting in the exit code 124, so we need to
         # ignore exit code 124.
         run: |
-          timeout 30 docker run -e DB_PORT='5432' \
+          timeout --preserve-status 30 docker run -e DB_PORT='5432' \
           -e REDIS_URL='redis://localhost:6379' \
           -e RATE_LIMIT_REDIS_URL='redis://localhost:6379' \
           -e NODE_ENV='test' \
           --network="host" \
-          service-base || ( [[ $? -eq 124 ]] && \
-            echo "Service container ran for 30 seconds with no errors" )
+          service-base || { 
+            exit_code=$?
+            if [ $exit_code -eq 124 ]; then
+              echo "Service container timed out after 30 seconds"
+              exit 0
+            else
+              echo "Service container failed with exit code $exit_code"
+              exit $exit_code
+            fi
+          }
